# Generated by Django 3.0.5 on 2020-04-16 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Verify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel', models.CharField(help_text='手机号码', max_length=11)),
                ('vcode', models.CharField(help_text='验证码', max_length=6)),
                ('send_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
