# Generated by Django 3.0.5 on 2020-04-16 01:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verify_code', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verify',
            name='send_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 16, 1, 56, 47, 363109)),
        ),
    ]
