# Generated by Django 3.0.5 on 2020-04-16 01:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('verify_code', '0002_auto_20200416_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verify',
            name='send_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
